import { GeneralKeys, KeyboardCodes } from "../../../../enums"

/**
 * QWERTY layout key-to-code mapping. \
 * Maps key values (including Shift variants) to their corresponding physical key codes. \
 * Used to set the `code` field on `KuaioCombination` so that matching can be code-first.
 */
export const qwertyKeyToCodeMap: Record<string, string> = {
  // Letters a-z
  [GeneralKeys.A]: KeyboardCodes.KeyA,
  [GeneralKeys.B]: KeyboardCodes.KeyB,
  [GeneralKeys.C]: KeyboardCodes.KeyC,
  [GeneralKeys.D]: KeyboardCodes.KeyD,
  [GeneralKeys.E]: KeyboardCodes.KeyE,
  [GeneralKeys.F]: KeyboardCodes.KeyF,
  [GeneralKeys.G]: KeyboardCodes.KeyG,
  [GeneralKeys.H]: KeyboardCodes.KeyH,
  [GeneralKeys.I]: KeyboardCodes.KeyI,
  [GeneralKeys.J]: KeyboardCodes.KeyJ,
  [GeneralKeys.K]: KeyboardCodes.KeyK,
  [GeneralKeys.L]: KeyboardCodes.KeyL,
  [GeneralKeys.M]: KeyboardCodes.KeyM,
  [GeneralKeys.N]: KeyboardCodes.KeyN,
  [GeneralKeys.O]: KeyboardCodes.KeyO,
  [GeneralKeys.P]: KeyboardCodes.KeyP,
  [GeneralKeys.Q]: KeyboardCodes.KeyQ,
  [GeneralKeys.R]: KeyboardCodes.KeyR,
  [GeneralKeys.S]: KeyboardCodes.KeyS,
  [GeneralKeys.T]: KeyboardCodes.KeyT,
  [GeneralKeys.U]: KeyboardCodes.KeyU,
  [GeneralKeys.V]: KeyboardCodes.KeyV,
  [GeneralKeys.W]: KeyboardCodes.KeyW,
  [GeneralKeys.X]: KeyboardCodes.KeyX,
  [GeneralKeys.Y]: KeyboardCodes.KeyY,
  [GeneralKeys.Z]: KeyboardCodes.KeyZ,
  // Digits 0-9
  [GeneralKeys.Digit0]: KeyboardCodes.Digit0,
  [GeneralKeys.Digit1]: KeyboardCodes.Digit1,
  [GeneralKeys.Digit2]: KeyboardCodes.Digit2,
  [GeneralKeys.Digit3]: KeyboardCodes.Digit3,
  [GeneralKeys.Digit4]: KeyboardCodes.Digit4,
  [GeneralKeys.Digit5]: KeyboardCodes.Digit5,
  [GeneralKeys.Digit6]: KeyboardCodes.Digit6,
  [GeneralKeys.Digit7]: KeyboardCodes.Digit7,
  [GeneralKeys.Digit8]: KeyboardCodes.Digit8,
  [GeneralKeys.Digit9]: KeyboardCodes.Digit9,
  // Base symbol keys (unshifted)
  [GeneralKeys.Backquote]: KeyboardCodes.Backquote,
  [GeneralKeys.Minus]: KeyboardCodes.Minus,
  [GeneralKeys.Equal]: KeyboardCodes.Equal,
  [GeneralKeys.BracketLeft]: KeyboardCodes.BracketLeft,
  [GeneralKeys.BracketRight]: KeyboardCodes.BracketRight,
  [GeneralKeys.Backslash]: KeyboardCodes.Backslash,
  [GeneralKeys.Semicolon]: KeyboardCodes.Semicolon,
  [GeneralKeys.Quote]: KeyboardCodes.Quote,
  [GeneralKeys.Comma]: KeyboardCodes.Comma,
  [GeneralKeys.Period]: KeyboardCodes.Period,
  [GeneralKeys.Slash]: KeyboardCodes.Slash,
  // Shifted symbol keys (same physical keys as their base)
  [GeneralKeys.Tilde]: KeyboardCodes.Backquote,
  [GeneralKeys.ExclamationMark]: KeyboardCodes.Digit1,
  [GeneralKeys.At]: KeyboardCodes.Digit2,
  [GeneralKeys.Number]: KeyboardCodes.Digit3,
  [GeneralKeys.Dollar]: KeyboardCodes.Digit4,
  [GeneralKeys.Percent]: KeyboardCodes.Digit5,
  [GeneralKeys.Caret]: KeyboardCodes.Digit6,
  [GeneralKeys.Ampersand]: KeyboardCodes.Digit7,
  [GeneralKeys.Asterisk]: KeyboardCodes.Digit8,
  [GeneralKeys.ParenthesisLeft]: KeyboardCodes.Digit9,
  [GeneralKeys.ParenthesisRight]: KeyboardCodes.Digit0,
  [GeneralKeys.Underscore]: KeyboardCodes.Minus,
  [GeneralKeys.Plus]: KeyboardCodes.Equal,
  [GeneralKeys.CurlyBracketLeft]: KeyboardCodes.BracketLeft,
  [GeneralKeys.CurlyBracketRight]: KeyboardCodes.BracketRight,
  [GeneralKeys.VerticalLine]: KeyboardCodes.Backslash,
  [GeneralKeys.Colon]: KeyboardCodes.Semicolon,
  [GeneralKeys.DoubleQuotes]: KeyboardCodes.Quote,
  [GeneralKeys.LessThan]: KeyboardCodes.Comma,
  [GeneralKeys.GreaterThan]: KeyboardCodes.Period,
  [GeneralKeys.QuestionMark]: KeyboardCodes.Slash
}
